export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const GET_SHOPPING_LISTS = 'GET_SHOPPING_LISTS';
export const GET_SHOPPING_LIST = 'GET_SHOPPING_LIST';
export const CREATE_SHOPPING_LIST = 'CREATE_SHOPPING_LIST';

export const GET_LIST_ITEMS = 'GET_LIST_ITEMS';
