export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const GET_SHOPPING_LISTS = 'GET_SHOPPING_LISTS';
export const GET_SHOPPING_LIST = 'GET_SHOPPING_LIST';
export const CREATE_SHOPPING_LIST = 'CREATE_SHOPPING_LIST';

export const GET_LIST_ITEMS = 'GET_LIST_ITEMS';
